# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GdocsMdFs < Formula
  desc "Mount Google Drive as a local FUSE filesystem with Google Docs as Markdown."
  homepage "https://github.com/sandgardenhq/gdocs-md-fs"
  version "0.1.1"
  license "MIT"

  depends_on "libfuse" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.1.1/gdocs-md-fs_v0.1.1_darwin-amd64.tar.gz"
      sha256 "d4d586fbb3b0dfc9373a8e4084b2726749bd2fe78e682c4db2b19254227f271c"

      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.1.1/gdocs-md-fs_v0.1.1_darwin-arm64.tar.gz"
      sha256 "99f3ec8df8dae5de4d46a597be39c763f0f7ea622c40747eec59fc8b98b26814"

      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.1.1/gdocs-md-fs_v0.1.1_linux-amd64.tar.gz"
      sha256 "0ceed548949176a33b44a907d54b5eb7f84b1dd9df9c8b7a31ac6334527ade8e"
      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.1.1/gdocs-md-fs_v0.1.1_linux-arm64.tar.gz"
      sha256 "d7e301357b134784d8af9d92d1bc03a96729111dd026cecc061eb776571b69c9"
      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
  end

  def caveats
    <<~EOS
      gdocs-md-fs requires FUSE.

      On macOS, install macFUSE separately:
        brew install --cask macfuse
      Then approve the macFUSE system extension in System Settings > Privacy &
      Security and reboot. macFUSE is not installed automatically because it is a
      kernel/system extension that requires manual approval and a restart.
    EOS
  end

  test do
    system "#{bin}/gdocs-md-fs", "version"
  end
end
