# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GdocsMdFs < Formula
  desc "Mount Google Drive as a local FUSE filesystem with Google Docs as Markdown."
  homepage "https://github.com/sandgardenhq/gdocs-md-fs"
  version "0.2.0"
  license "MIT"

  depends_on "libfuse" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.2.0/gdocs-md-fs_v0.2.0_darwin-amd64.tar.gz"
      sha256 "c98344abdd31e0d245aac18a4074089a032094b2c4f70f8d0d41e306933d4466"

      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.2.0/gdocs-md-fs_v0.2.0_darwin-arm64.tar.gz"
      sha256 "5286abb34df1b3fab39cd03f488b2e27e17a1886f2c9141f9c81d72fad30b72e"

      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.2.0/gdocs-md-fs_v0.2.0_linux-amd64.tar.gz"
      sha256 "d4c27db640a0836ece456f5218c29101cc3d66d8a2c0dac1fc89e09f262bafb8"
      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.2.0/gdocs-md-fs_v0.2.0_linux-arm64.tar.gz"
      sha256 "b034ed4a93f152d83774ca50e78365c53541d04fa42abd58af9c29e598f94817"
      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
  end

  def caveats
    <<~EOS
      gdocs-md-fs requires FUSE.

      On macOS, install macFUSE separately:
        brew install --cask macfuse
      Then approve the macFUSE system extension in System Settings > Privacy &
      Security and reboot. macFUSE is not installed automatically because it is a
      kernel/system extension that requires manual approval and a restart.
    EOS
  end

  test do
    system "#{bin}/gdocs-md-fs", "version"
  end
end
