# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GdocsMdFs < Formula
  desc "Mount Google Drive as a local FUSE filesystem with Google Docs as Markdown."
  homepage "https://github.com/sandgardenhq/gdocs-md-fs"
  version "0.3.0"
  license "MIT"

  depends_on "libfuse" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.3.0/gdocs-md-fs_v0.3.0_darwin-amd64.tar.gz"
      sha256 "4257f6093c7ce5e40402cf25a139690ed23b2a64169ee2cd1f5c4b9af548d16a"

      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.3.0/gdocs-md-fs_v0.3.0_darwin-arm64.tar.gz"
      sha256 "f5b209ec377e22cc7ebcade931099d2dbbbd9ac5e9ceb65b0ee90a3ee3d42ee9"

      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.3.0/gdocs-md-fs_v0.3.0_linux-amd64.tar.gz"
      sha256 "949469245b8d205452bc798b66fd623f04617120fca7b3baacc5465b5bd3f035"
      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandgardenhq/gdocs-md-fs/releases/download/v0.3.0/gdocs-md-fs_v0.3.0_linux-arm64.tar.gz"
      sha256 "5fdda81b7798a26080351f318d57c8769985ddd8a1a05a357675fbecac12a591"
      define_method(:install) do
        bin.install "gdocs-md-fs"
      end
    end
  end

  def caveats
    <<~EOS
      gdocs-md-fs requires FUSE.

      On macOS, install macFUSE separately:
        brew install --cask macfuse
      Then approve the macFUSE system extension in System Settings > Privacy &
      Security and reboot. macFUSE is not installed automatically because it is a
      kernel/system extension that requires manual approval and a restart.
    EOS
  end

  test do
    system "#{bin}/gdocs-md-fs", "version"
  end
end
