# frozen_string_literal: true

# Generated by packages/collector/scripts/build-packaging-assets.mjs (#1229).
# Do not edit by hand: every Miranda publish overwrites it.
class MirandaCollector < Formula
  desc "Collector that reports coding-agent token usage to Miranda"
  homepage "https://miranda.co"
  version "26.9.41254"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-8b2b5db0eaab/miranda-collector-darwin-arm64"
      sha256 "187a6767fd90b4d9195793c9d41f7a9fab5f47f1447c7fff6e72952970ac405d"
    end
    on_intel do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-8b2b5db0eaab/miranda-collector-darwin-x64"
      sha256 "652dbce84bffb9eb84b19f9ba3680d9e794322b3d5d42088d63b5078c3550e7f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-8b2b5db0eaab/miranda-collector-linux-arm64"
      sha256 "32f64bba32ee2ded023dc503989079f3e9f5cebef0756f5e56f8a62c8a848392"
    end
    on_intel do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-8b2b5db0eaab/miranda-collector-linux-x64"
      sha256 "65d4f6aafe6b81d10fdd9b29945ff4d40aad03812cf70004e7dc2dcad235cd1f"
    end
  end

  def install
    # The release asset is named per platform; the command a user types is not.
    bin.install Dir["miranda-collector-*"].first => "miranda-collector"
  end

  service do
    run [opt_bin/"miranda-collector", "daemon", "run"]
    keep_alive true
    run_type :immediate
    log_path var/"log/miranda-collector.log"
    error_log_path var/"log/miranda-collector.log"
  end

  test do
    # Exercised with no config.json, which is the state every fresh install is
    # in: the collector must report rather than crash.
    assert_match "daemon", shell_output("#{bin}/miranda-collector daemon status")
  end
end
