# frozen_string_literal: true

# Generated by packages/collector/scripts/build-packaging-assets.mjs (#1229).
# Do not edit by hand: every Miranda publish overwrites it.
class MirandaCollector < Formula
  desc "Collector that reports coding-agent token usage to Miranda"
  homepage "https://miranda.co"
  version "26.10.2380"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-c31ac6470e26/miranda-collector-darwin-arm64"
      sha256 "077839799bd101fa222fda482c1997c9f6cf52e8921c4bc05d206ce538256ea2"
    end
    on_intel do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-c31ac6470e26/miranda-collector-darwin-x64"
      sha256 "e7e40442d8f24e7c78d60e496bc1576d55fa2ee4ee885de21906bb7ca2817583"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-c31ac6470e26/miranda-collector-linux-arm64"
      sha256 "c1d71cfc011d28a12de261e49ca039d069d7aaea826dc5deba5550a00da1fff3"
    end
    on_intel do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-c31ac6470e26/miranda-collector-linux-x64"
      sha256 "1b4a325487b43a35a1bda7a69ac1b687752e67f14cbee40d22c43dccdf1e96b5"
    end
  end

  def install
    # The release asset is named per platform; the command a user types is not.
    bin.install Dir["miranda-collector-*"].first => "miranda-collector"
  end

  service do
    run [opt_bin/"miranda-collector", "daemon", "run"]
    keep_alive true
    run_type :immediate
    log_path var/"log/miranda-collector.log"
    error_log_path var/"log/miranda-collector.log"
  end

  test do
    # Exercised with no config.json, which is the state every fresh install is
    # in: the collector must report rather than crash.
    assert_match "daemon", shell_output("#{bin}/miranda-collector daemon status")
  end
end
