# frozen_string_literal: true

# Generated by packages/collector/scripts/build-packaging-assets.mjs (#1229).
# Do not edit by hand: every Miranda publish overwrites it.
class MirandaCollector < Formula
  desc "Collector that reports coding-agent token usage to Miranda"
  homepage "https://miranda.co"
  version "26.10.2711"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-5e99a6fe785e/miranda-collector-darwin-arm64"
      sha256 "074bbad4d37670b5b5dc00daecba845c41e7b5019dd62620787ff17af5848076"
    end
    on_intel do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-5e99a6fe785e/miranda-collector-darwin-x64"
      sha256 "517b11e91f91ee831ce2f0b465ebb941e9c3aae4de13aa5659bab239d22a310d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-5e99a6fe785e/miranda-collector-linux-arm64"
      sha256 "1a74019c29edb49501134a2f03ed185730c288a2b75c42bf3cf9e0199132b2c6"
    end
    on_intel do
      url "https://github.com/sandgardenhq/miranda/releases/download/collector-5e99a6fe785e/miranda-collector-linux-x64"
      sha256 "acb5beef78b60f0450f44b00fe8b7150b08f7e2f7bcc971049287a1b596011a2"
    end
  end

  def install
    # The release asset is named per platform; the command a user types is not.
    bin.install Dir["miranda-collector-*"].first => "miranda-collector"
  end

  service do
    run [opt_bin/"miranda-collector", "daemon", "run"]
    keep_alive true
    run_type :immediate
    log_path var/"log/miranda-collector.log"
    error_log_path var/"log/miranda-collector.log"
  end

  test do
    # Exercised with no config.json, which is the state every fresh install is
    # in: the collector must report rather than crash.
    assert_match "daemon", shell_output("#{bin}/miranda-collector daemon status")
  end
end
